### ISSUE TITLE
carga de datos

### ISSUE THREAD

**Issue by JuanJoZP** [JuanJoZP/bolsa-track#2]
cargar los datos del excel (solo los estaticos) y crear datos de ejemplo para las tablas de las que no tenemos datos como usuario

**Comment by NoT-Serna** [comment]
Ya en el github esta los comandos en sql para la carga masiva, yo ya tengo todo funcionando en mi postgres, entonces para que lo tengan en su máquina es copiar las tablas, descargar los archivos excel del documento y ya queda funcionando
